on:
  push:
     branches:
       - main

name: blogdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages("renv", "blogdown")'
          R -e 'renv::restore()'
          
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo()'
          
      - name: Build site
        run: |
          R -e 'blogdown::build_site(TRUE)'
          
      - name: Install npm
        uses: actions/setup-node@v1

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secret EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         email:  ${{ secrets.EMAIL }} # must be a verified email
         build_dir: ./public                     # "_site/" by default


